### PR TITLE
Updated UI for DCALL

### PR DESCRIPTION
**Pull request by CDPhu**
Please tell me if I should change anything in this. Issue #1

### CODE REVIEW

**Comment by Mukundan314** [comment]
- solid color instead of gradients
  - wanted to avoid shadows
  - having everything vertically centered on the home page

**Comment by CDPhu** [comment]
the shadows were needed for that neat little glow effect of the search bar. but it should be in the middle, and the buttons should no longer be gradient

**Comment by Mukundan314** [comment]
image

(left is chrome, right is firefox)
the search bar does not seem to be centered vertically, what browser are you using?

everything else looks good

**Comment by CDPhu** [comment]
I think this is what you meant for me to do. Sorry, I misunderstood, Horizontally and Vertically.

**Comment by Mukundan314** [comment]
It is still not centered for me; merging for now since everything else look good.

**Pull request merged**
